### ISSUE TITLE
Broken README links

### ISSUE THREAD

**Issue by iam-py-test** [chirag127/adblock#7]
Some of the links in the README - i.e. https://raw.githubusercontent.com/chirag127/adblock/main/SP/C.txt - are outdated and broken (lead to 404)

**Comment by chirag127** [comment]
https://github.com/chirag127/adblock/commit/24da87d2a4e63a052c1c876fb7db636fd32cc0d9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by chirag127** [comment]
Hmm.. I have amended the other links too in further commits.
