### ISSUE TITLE
Description on https://raw.githubusercontent.com/chirag127/adblock/main/adtl/ageconfirmation.txt is wrong

### ISSUE THREAD

**Issue by iam-py-test** [chirag127/adblock#8]
The description on https://raw.githubusercontent.com/chirag127/adblock/main/adtl/ageconfirmation.txt is _It block the donations blocker_ but that's not what this list does

**Comment by chirag127** [comment]
https://github.com/chirag127/adblock/commit/73238d9d91b5e46ac19259093e72986946881343
